### ISSUE TITLE
How to stop the server from listening?

### ISSUE THREAD

**Issue by jamiesoncj** [validityhq/node-sftp-server#55]
Hello, apologies for opening an issue for this but I couldn't find out how to do this from the docs or reading the code.

Is there a way to stop the server from listening? At the moment I am using this great package as part of a test suite and would like to start and stop different instances of the server at various points in the suite, listening on the same port.

Can it be done using the existing code, or is there a need for a PR to add this?

If the latter, I would be happy to help - would love a point in the right direction if so.

Thanks for a great package, I tried several similar that weren't suitable before I found this one :smile:

**Comment by lqueryvg** [comment]
I have the same use case.

I want to use this for integration testing, but I don't know how to stop it at the end of the test, so my tests just hang !

**Comment by aterna01** [comment]
It's not documented but you can try this 
```
srv.on("end", function () {
    console.warn("User is disconnected");
    return srv.server.close();
  });
```

**Comment by jamiesoncj** [comment]
Thank you @aterna01 for your help - this was exactly what I needed.
